# Generated by Django 3.0.6 on 2020-05-21 03:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to='media'),
        ),
    ]
