# Generated by Django 3.0.6 on 2020-05-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20200521_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
