# Generated by Django 3.0.6 on 2020-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20200525_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='imageid',
            field=models.IntegerField(default=0),
        ),
    ]
