# Generated by Django 3.0.6 on 2020-06-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_auto_20200608_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='images',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='images',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
