# Generated by Django 3.0.6 on 2020-06-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20200609_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='votes',
        ),
    ]
