# Generated by Django 3.0.6 on 2020-06-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_delete_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_vote',
        ),
    ]
